sudo: required

language: node_js

node_js: '14'

cache:
  yarn: true
  directories:
    - node_modules

git:
    submodules: false

before_install:
    - git submodule update --init --recursive
    
script:
  - ./build.sh

before_deploy:
  - export VSIX_FILE=$(ls extension/oml-luxor\-*.vsix)

deploy:
  - provider: releases
    api_key:
      secure: "bHlEyN5r2zgcK4kYu5IU4ZNvzHeHE+qNHI3z6c/k+OBAh68v6uFIBT7LuBbA0P8mttHtnwrgw2ax61BLfD9XEMG9YoJG6FoCxlOVH6LLdIHaX+iLUv8QnX09pm6RY1gqnS0qJttxTGMCP2F5ecvM8KY7UUSLn9YLOsA+wfkYd+IMu1r4zFVuuRjjXZ9hULKAdLVt3D5YcTMmhdAvB+rbKidw3xRCof4X9Bj1sF+5fERhz75zENMEFJl95uiBrRPKlpc2fL65AINmEsKXXpBWmBwm2bOypqbdygPxh1y5WL3GSHD+cl4ogx5rC6hgIv+nHnFi+IgxdGQ/+Ue214v9azZzCG0Sm3IY2afAwKLSCKH+6MBVZFKwLVmHUMQiJQNt6tSvMAkmGBZv8BoimPetjzHzcmu5LIK+/vduc1vZUeMCAdsVrluYOCx5yadY4jpcFYMUllXhekZEeBSPznrlZsvSzYGeyKPQLIc9+HbcxQPdZ8SZ6FW963fiDFwynMWTlAVos+SaJ2gY6k1JH2ddRzfbAANyWNxBouvRg75T/R5R361urtJ5QVwjPlrq5H5oOnFYyxr2gNbCGtzj/9mPvvlrgGxnPVKHO75hgqv5l/qti2SfVvIrJUMrjMzB861yCx16BFvMLokyKysJss3C9LhOyCO4E478ntMmaw7GFlw="
    file_glob: true
    file: "${VSIX_FILE}"
    skip_cleanup: true
    on:
      tags: true
      branch: master
  - provider: script
    script: "npx ovsx publish ${VSIX_FILE} -p ${OVSX_API_TOKEN}"
    skip_cleanup: true
    on:
      tags: true
      branch: master
