name: CD

on:
  release:
    types: [published]
      
jobs:
  publish:

    runs-on: ubuntu-latest
    permissions: write-all
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14.x
        
    - name: Build extension
      run: ./build.sh
    
    - name: Publish extension
      uses: softprops/action-gh-release@v1
      with:
        files: extension/oml-luxor\-*.vsix
